# portfolio-manager-be/k8s/nexus-secret.yaml
apiVersion: v1
kind: Secret
metadata:
  name: nexus-registry-secret
  namespace: portfolio-manager
data:
  # Base64でエンコードされた認証情報 (admin:admin123, 192.168.56.1:8082)
  .dockerconfigjson: ewogICAgImF1dGhzIjogewogICAgICAgICIxOTIuMTY4LjU2LjE6ODA4MiI6IHsgCiAgICAgICAgICAgICJhdXRoIjogIllXUm1hMDRvZFd0YWJtaW4xMjM9IgogICAgICAgIH0KICAgIH0KfQ== 
type: kubernetes.io/dockerconfigjson